### ISSUE TITLE
Problems with SortingIcon when reordering columns

### ISSUE THREAD

**Issue by TheStone03** [akgulebubekir/Maui.DataGrid#122]
**Describe the bug**
I changed the HeaderGrid in a CollectionView for re-order the columns from there, but if i sort a specific column and then move it, when i try to sort again that column, an Exception is thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll (No installed components were detected)

**Comment by symbiogenesis** [comment]
Is this with version 3.0 ?

**Comment by TheStone03** [comment]
yes, it should be version 3.0.

sry for late reply but i was on holiday ;)

**Comment by symbiogenesis** [comment]
This may require new sorting logic that works based on the property name, rather than the index. Since the index could change.

We will probably leave the index approach for backwards compatibility, but if you sent a working PR that solves the issue using an additional bindable property, and leave the existing ones, then you could post it for review


Here's some thoughts to get you started:


1. **Update the `SortData` class to include the `PropertyName` instead of the index.** This way, you can identify the column to sort by its property name, which remains consistent even if the columns are reordered.

2. **Modify the `CanSort` method to find the column by its property name.**

3. **Update the `GetSortedItems` method to find the column by its property name.**


```csharp
// Modify the SortData class to include the PropertyName
public class SortData
{
    public string PropertyName { get; set; }
    public SortingOrder Order { get; set; }

    public SortData(string propertyName, SortingOrder order)
    {
        PropertyName = propertyName;
        Order = order;
    }
}

// Update the CanSort method
private bool CanSort(SortData? sortData)
{
    // ...
    if (sortData?.PropertyName == null)
    {
        Console.WriteLine($"Please set the {nameof(sortData.PropertyName)} of the column");
        return false;
    }
    var columnToSort = Columns.FirstOrDefault(c => c.PropertyName == sortData.PropertyName);
    // ...
}

// Update the GetSortedItems method
private IList<object> GetSortedItems(IList<object> unsortedItems, SortData sortData)
{
    var columnToSort = Columns.FirstOrDefault(c => c.PropertyName == sortData.PropertyName);
    // ...
}

// Update the SortAndPaginate method
private void SortAndPaginate(SortData? sortData = null)
{
    // ...
    if (sortData != null && CanSort(sortData))
    {
        sortedItems = GetSortedItems(originalItems, sortData);
    }
    // ...
}

// Update the TapGestureRecognizer Command in the GetHeaderCell method
var sortRecognizer = new TapGestureRecognizer
{
    Command = new Command(() =>
    {
        var order = column.SortingOrder == SortingOrder.Ascendant ? SortingOrder.Descendant : SortingOrder.Ascendant;
        SortedColumnIndex = new SortData(column.PropertyName, order);
        column.SortingOrder = order;
    }, () => column.SortingEnabled)
};
```

These changes may ensure that the sorting mechanism identifies the correct column to sort, even after the columns have been reordered.

**Comment by TheStone03** [comment]
> Can you build a reproducible test case, and link the repository?

I link the Repo i've been working where i have this problem: https://github.com/leonianto/Test.Maui.DataGrid/tree/temp

Maybe if it could be also a feature directly implemented in your DataGrid because a lot of licensed DataGrid has this. Thanks

**Comment by symbiogenesis** [comment]
I believe that I just fixed this as of commit: https://github.com/akgulebubekir/Maui.DataGrid/commit/7361ece12a48c3efb2f5a93c55be2f58e73d8ba5
